show_featured_categories:
  type: bool
  default: true
  description: "Display the Featured Categories section of the homepage."
featured_categories:
  type: list
  list_type: category
  default: ""
  description: "Select which categories to showcase in the Featured Categories section."